ALTER TABLE "clubs" ADD COLUMN "in_house" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
-- Gardens Galleria clubs (add-only; existing slugs are left alone)
INSERT INTO "cities" ("name", "slug", "state", "sort_order", "is_active") VALUES ('Noida', 'noida', 'Uttar Pradesh', 3, true) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Impulse', 'impulse-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', '1st Floor, Gardens Galleria Mall, Sector 38A, Noida', 'SyncOut House — premium crowd, full kitchen and bar', 'Our in-house club on the first floor of Gardens Galleria. A big, bright room made for birthdays and big groups, a full kitchen and bar, and a door our own team runs — so the list you''re on is the list they check. Bollywood and commercial sets till late.', '/clubs/impulse-gardens-galleria.svg', '["/clubs/impulse-gardens-galleria.svg"]'::jsonb, '["Bollywood","Commercial","House"]'::jsonb, '["SyncOut House","Premium crowd","Food & drinks","Big groups"]'::jsonb, NULL, '12:00 PM', '1:00 AM', NULL, 0, true, true, -40) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Levernasia', 'levernasia-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', '205–206, 1st Floor, Gardens Galleria Mall, Sector 38A, Noida', 'SyncOut House — LA-style club with a world kitchen', 'An LA-inspired room with a VDJ booth, statement lighting and a kitchen that goes from Japanese and Italian to North Indian. One of our in-house clubs: premium crowd, signature cocktails, food on every table and our team on the door.', '/clubs/levernasia-gardens-galleria.svg', '["/clubs/levernasia-gardens-galleria.svg"]'::jsonb, '["Bollywood","Commercial","Hip-hop"]'::jsonb, '["SyncOut House","Premium crowd","Food & drinks","VDJ"]'::jsonb, 2500, '12:15 PM', '1:00 AM', NULL, 0, true, true, -39) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Millionaire The Lux Club', 'millionaire-the-lux-club-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', '320–326, 2nd Floor, Gardens Galleria Mall, Sector 38A, Noida', 'SyncOut House — luxe nights on the second floor', 'Plush, gold-lit and made for dressing up: Bollywood Saturdays and themed weeknights, with a kitchen doing North Indian, Chinese and bar bites. Our in-house club — premium crowd, food and drinks, our own door.', '/clubs/millionaire-the-lux-club-gardens-galleria.svg', '["/clubs/millionaire-the-lux-club-gardens-galleria.svg"]'::jsonb, '["Bollywood","Commercial","Punjabi"]'::jsonb, '["SyncOut House","Premium crowd","Food & drinks","Luxe"]'::jsonb, 3500, '12:00 PM', '1:30 AM', NULL, 0, true, true, -38) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Club BMD', 'club-bmd-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', 'Ground Floor, Gardens Galleria Mall, Sector 38A, Noida', 'A ground-floor party room built for celebrations', 'A party-first room on the ground floor — popular for birthdays and group nights, with a dance floor that fills up after ten.', '/clubs/club-bmd-gardens-galleria.svg', '["/clubs/club-bmd-gardens-galleria.svg"]'::jsonb, '["Bollywood","Commercial"]'::jsonb, '["Club","Party venue"]'::jsonb, NULL, '12:00 PM', '1:00 AM', NULL, 0, false, false, -37) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Toy Boy', 'toy-boy-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', 'Gardens Galleria Mall, Gardens Galleria Mall, Sector 38A, Noida', 'Stylish room, energetic crowd', 'A trendy club with a dressed-up crowd and a floor that stays busy on weekends.', '/clubs/toy-boy-gardens-galleria.svg', '["/clubs/toy-boy-gardens-galleria.svg"]'::jsonb, '["Commercial","House"]'::jsonb, '["Club"]'::jsonb, NULL, '12:00 PM', '1:00 AM', NULL, 0, false, false, -36) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Big Boyz Lounge', 'big-boyz-lounge-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', 'C2A, Gardens Galleria Mall, Sector 38A, Noida', 'Lounge with an outdoor terrace', 'A relaxed lounge with outdoor seating for groups — good for starting the night before heading upstairs.', '/clubs/big-boyz-lounge-gardens-galleria.svg', '["/clubs/big-boyz-lounge-gardens-galleria.svg"]'::jsonb, '["Bollywood","Punjabi"]'::jsonb, '["Lounge","Outdoor seating"]'::jsonb, 2000, '12:00 PM', '1:00 AM', NULL, 0, false, false, -35) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Dearie', 'dearie-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', '1st Floor, Gardens Galleria Mall, Sector 38A, Noida', 'Lounge with a balcony over the mall', 'A first-floor lounge with a balcony — cocktails, music and a view of the Galleria crowd.', '/clubs/dearie-gardens-galleria.svg', '["/clubs/dearie-gardens-galleria.svg"]'::jsonb, '["Commercial","Bollywood"]'::jsonb, '["Lounge","Balcony"]'::jsonb, NULL, '12:00 PM', '1:00 AM', NULL, 0, false, false, -34) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Ru-Bar-Ru, Gardens Galleria', 'ru-bar-ru-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', 'Ground Floor, Gardens Galleria Mall, Sector 38A, Noida', 'Upscale bar at the mall entrance', 'Right at the entrance on the ground floor — an upscale bar and kitchen with inventive cocktails and a dressed-up crowd.', '/clubs/ru-bar-ru-gardens-galleria.svg', '["/clubs/ru-bar-ru-gardens-galleria.svg"]'::jsonb, '["Commercial","Bollywood"]'::jsonb, '["Upscale","Cocktails"]'::jsonb, 3000, '12:00 PM', '1:00 AM', NULL, 0, false, false, -33) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Lord of the Drinks, Noida', 'lord-of-the-drinks-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', '1st Floor, Gardens Galleria Mall, Sector 38A, Noida', 'Grand gastropub with a live DJ', 'A big, grand-looking gastropub with a live DJ and a long menu — a reliable pick for groups.', '/clubs/lord-of-the-drinks-gardens-galleria.svg', '["/clubs/lord-of-the-drinks-gardens-galleria.svg"]'::jsonb, '["Commercial","Bollywood"]'::jsonb, '["Gastropub","Live DJ"]'::jsonb, NULL, '12:00 PM', '1:00 AM', NULL, 0, false, false, -32) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Imperfecto, Gardens Galleria', 'imperfecto-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', 'Shop 341–342, Gardens Galleria Mall, Sector 38A, Noida', 'Rooftop gastropub at the edge of the mall', 'A rooftop gastropub at the edge of Gardens Galleria — easy, lively and good for a big table.', '/clubs/imperfecto-gardens-galleria.svg', '["/clubs/imperfecto-gardens-galleria.svg"]'::jsonb, '["Commercial","Bollywood"]'::jsonb, '["Rooftop","Gastropub"]'::jsonb, 2000, '12:00 PM', '1:00 AM', NULL, 0, false, false, -31) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('The Smoke Factory', 'the-smoke-factory-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', 'Gardens Galleria Mall, Gardens Galleria Mall, Sector 38A, Noida', 'Live music and a big menu', 'Known for live music and a long food menu — a sit-down that turns into a party.', '/clubs/the-smoke-factory-gardens-galleria.svg', '["/clubs/the-smoke-factory-gardens-galleria.svg"]'::jsonb, '["Live","Commercial"]'::jsonb, '["Live music","Gastropub"]'::jsonb, NULL, '12:00 PM', '1:00 AM', NULL, 0, false, false, -30) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Growl', 'growl-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', '311–312, 2nd Floor, Gardens Galleria Mall, Sector 38A, Noida', 'Second-floor bar with ladies'' nights', 'A second-floor bar that does ladies'' nights well — loud, social and easy to reach from the escalators.', '/clubs/growl-gardens-galleria.svg', '["/clubs/growl-gardens-galleria.svg"]'::jsonb, '["Commercial","Bollywood"]'::jsonb, '["Bar","Ladies night"]'::jsonb, NULL, '12:00 PM', '1:00 AM', NULL, 0, false, false, -29) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Xero Courtyard', 'xero-courtyard-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', 'Shop 138, Gardens Galleria Mall, Sector 38A, Noida', 'Open courtyard bar', 'An open, courtyard-style bar for groups who want air and a long table before the clubs.', '/clubs/xero-courtyard-gardens-galleria.svg', '["/clubs/xero-courtyard-gardens-galleria.svg"]'::jsonb, '["Commercial","Retro"]'::jsonb, '["Courtyard","Bar"]'::jsonb, 2400, '12:00 PM', '1:00 AM', NULL, 0, false, false, -28) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "clubs" ("name", "slug", "city_slug", "area", "address", "tagline", "description", "cover_image", "gallery", "music_types", "tags", "price_for_two", "open_time", "close_time", "rating", "review_count", "is_featured", "in_house", "sort_order") VALUES ('Illuzion Luxe Club', 'illuzion-luxe-club-gardens-galleria', 'noida', 'Gardens Galleria, Sector 38A', 'Gardens Galleria Mall, Gardens Galleria Mall, Sector 38A, Noida', 'Luxury club, big-room sound', 'A newer luxury club that mixes big-room sound with a sleek, lit-up interior.', '/clubs/illuzion-luxe-club-gardens-galleria.svg', '["/clubs/illuzion-luxe-club-gardens-galleria.svg"]'::jsonb, '["House","Commercial"]'::jsonb, '["Club","Luxury"]'::jsonb, NULL, '12:00 PM', '1:00 AM', NULL, 0, false, false, -27) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
UPDATE "clubs" SET "in_house" = true, "is_featured" = true WHERE "slug" IN ('impulse-gardens-galleria', 'levernasia-gardens-galleria', 'millionaire-the-lux-club-gardens-galleria');
